# Generated by Django 5.1.4 on 2025-01-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worldcities',
            fields=[
                ('city', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lng', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'worldcities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
