# Generated by Django 5.1.4 on 2025-01-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GutenbergApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
    ]
